version: '3.6'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase01
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: "root"
      MB_DB_PASS: "root"
      MB_DB_HOST: db01
    networks:
      - metanet1
    depends_on:
      - db01
  db01:
    image: postgres:latest
    container_name: postgres-metabase
    environment:
      POSTGRES_USER: "root"
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: "root"
    networks:
      - metanet1
    ports:
     - 5433:5432
networks:
  metanet1:
    driver: bridge
