---
- hosts: webserver
  # become: true
  tasks:
    - name: Install nix packages
      apt: name={{item}} state=present update_cache=no
      with_items:
        - jq
        - curl

    - name: Getting metabase setup-token
      uri:
        url: "{{ lookup('env','METABASE_HOST') }}api/session/properties"
        method: GET
        return_content: yes
        body_format: json
        status_code: 200
      register: setupToken

    - name: Debug metabase setup-token
      debug:
        msg: "{{ setupToken.json['setup-token'] }}"

    - name: Register admin user
      uri:
        url: "{{ lookup('env','METABASE_HOST') }}api/setup"
        async: 300
        poll: 10
        method: POST
        return_content: yes
        body_format: json
        body:
          {
            "prefs": { "allow_tracking": true, "site_name": "teste" },
            "token": "{{ setupToken.json['setup-token'] }}",
            "user":
              {
                "first_name": "teste",
                "password": "12345678",
                "last_name": "teste",
                "email": "teste@teste.teste",
              },
          }
        status_code: 200
      register: adminId

    - name: Debug metabase Admin-ID
      debug:
        msg: "{{ adminId.json }}"

    - name: Adding the ADM_ID into .env file
      lineinfile:
        dest=/usr/app/.env line='export METABASE_ADM_ID={{ adminId.json.id }}'
        state=present create=yes

    - name: Enable embedding
      uri:
        url: "{{ lookup('env','METABASE_HOST') }}api/setting/enable-embedding"
        method: PUT
        headers:
          Cookie: "metabase.SESSION={{ adminId.json.id }}"
        body_format: json
        body: { value: true }
        status_code: 204
      register: enable_embedd

    - name: Putting embedd key up
      uri:
        url: "{{ lookup('env','METABASE_HOST') }}api/setting/embedding-secret-key"
        method: PUT
        headers:
          Cookie: "metabase.SESSION={{ adminId.json.id }}"
        body_format: json
        body:
          {
            value: "2adbc055dda8dcafba18d5949ef564ada8b8533a54f3b0ccf125d1441c0c4cd3",
          }
        status_code: 204

    - name: Getting embedding key
      uri:
        url: "{{ lookup('env','METABASE_HOST') }}api/setting/embedding-secret-key"
        return_content: yes
        method: GET
        headers:
          Content-Type: "application/json"
          Cookie: "metabase.SESSION={{ adminId.json.id }}"
        status_code: 200
      register: embed_id
    - debug:
        msg: "{{ embed_id.content }}"

    - name: Adding the EMBED_KEY into .env file
      lineinfile:
        dest=/usr/app/.env line='export METABASE_EMBED_KEY={{ embed_id.content }}'
        insertafter='EOF' state=present create=yes
